### ISSUE TITLE
Add single-database importer

### ISSUE THREAD

**Issue by rpsu** [Exove/local-docker#102]
## Overview
Running database import using some other than the one produced by `./ld dump` (all databases, including MySQL database) fails. 

## Proposed solution

Add a new command to import a single database
`./ld import-db PATH [NAME]`
where the full path to the db dump (.tar.gz?) is defined and NAME defaults to the one set in `.ld.config` / `MYSQL_DATABASE` (probably `drupal`).

## This issue is resolved when:
- [ ] user can import database to the DB container from a single database's dump file.

**Comment by kekkis** [comment]
See my comment in the PR to see how my solution deviates from the proposed solution.
