### ISSUE TITLE
Move drupal sites/XX/files -folders out of docker-sync

### ISSUE THREAD

**Issue by rpsu** [Exove/local-docker#127]
## Overview
Syncing HUGE amounts of files which do not need to be in highest-perfomant mount/share. 

Hence we can move out web/sites/*/files from the docker-sync and replace it with slower NFS sync. 

## What are the steps required to reproduce the bug?
Load loads of files, (10's of thousands, 10 Gb) of files into sites files folder and wait forever to the initial sync to be over.

## What behavior were you expecting?
faster startup sync

## What happened instead?
slow startup sync

## Proposed solution
Move `${APP_ROOT}/web/sites/default/files` out of docker-sync (`ignore` -rule) and create a NFS share for them spesifically.

## This issue is resolved when:
- initial sync ignores sites/xx/files -folder, but the content is present inside the container and on host

**Comment by kekkis** [comment]
One comment: based on what happens in Vagrant I predict that using NFS for files sync will result in permission issues. The UID presented by NFS will be 501 also in the container. Traditionally even 777 permissions have not worked optimally, but let's hope that things are better here.

**Comment by rpsu** [comment]
yes, that is the case. I droppped the NFS in favor of native docker mount (:cached) in one project due to this very reason. There is no significant performance gain to win with NFS, but loads of hassle with permissions and uid/guid mappings. IMHO now worth a fight.

**Comment by rpsu** [comment]
moving this forward to the next planned release.
