### ISSUE TITLE
Incorrect error message on command failure

### ISSUE THREAD

**Issue by hirvinen** [Exove/local-docker#137]
## Overview

If a command returns a nonzero exit status, ld erroneously prints the error that the command hook is missing.

## What are the steps required to reproduce the bug?

Example, but applies to any command that can return with a nonzero exit status:

1. Follow steps for setting up local-docker with a Skeleton project.
2. Get a warning that project is already created and that one should run `./ld up && ./ld composer install`

## What behavior were you expecting?

No warning about missing hook.

## What happened instead?

Got an error about a missing hook: `ERROR: Command not found (hook 'ld_command_init_exec' missing for command init)..`

## Proposed solution

Restructure ld.sh error handling

## This issue is resolved when:
- [ ] Errors for "hook not found" and command failure are handled separately.

**Comment by rpsu** [comment]
Fixed #138
