### ISSUE TITLE
Container nodejs is broken

### ISSUE THREAD

**Issue by hirvinen** [Exove/local-docker#145]
## Overview

The image used for the nodejs container, [wodby/drupal-node:1.0-1.0.0](https://hub.docker.com/r/wodby/drupal-node) seems to be broken.

## What are the steps required to reproduce the bug?

1. Follow the README instructions for compiling css.

## What behavior were you expecting?

Working styles on the site.

## What happened instead?

No styles.
Log output for nodejs container:
`
$ docker-compose logs -f nodejs
Attaching to PROJECT_nodejs
nodejs_1    | /usr/local/bin/docker-entrypoint.sh: line 9: /var/www/html/node_modules/drupal-node.js/nodejs.config.js: No such file or directory
PROJEC_nodejs exited with code 1
`

## Proposed solution

?

## This issue is resolved when:
- [ ] A working nodejs container is provided.

**Comment by rpsu** [comment]
This seems to have been fixed by 8a006719418ddcb7550fcb59278acbbcf7bb03ee
