### ISSUE TITLE
Consider having ssh command for accessing the container.

### ISSUE THREAD

**Issue by ivangsp** [Exove/local-docker#181]
Currently one can access the container by running `docker-compose exec php bash`, it would be nice if we can have a command like `./ld ssh` that does the same thing  - similar to that in **ddev** and **vagrant**.

**Comment by LorenzoCoronati** [comment]
https://github.com/Exove/local-docker/pull/56
you can use this, even if not merged yet

**Comment by rpsu** [comment]
https://docs.docker.com/docker-for-mac/osxfs/#ssh-agent-forwarding
