### ISSUE TITLE
ld fails when .env file does not exist

### ISSUE THREAD

**Issue by lorecoro** [Exove/local-docker#49]
## Overview
ld fails when .env file does not exist

## What are the steps required to reproduce the bug?
run ld right after clone

## What behavior were you expecting?
something :-)

## What happened instead?
nothing

## Proposed solution
import_root_env should return 1 even if .env file is not found

## This issue is resolved when:
- import_root_env returns 1 even if .env file is not found

**Comment by rpsu** [comment]
Fixed by #51
